name: ansattporten
networks:
  idporten:
    name: idporten

services:
  democlient:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      spring_profiles_active: docker
    ports:
      - "7074:7074"
    networks:
      - idporten
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -jar application.jar