---
server:
  port: 7074
  servlet:
    context-path: /idporten-oidc-demo-client
    session:
      tracking-modes:
        - cookie  # to block session via url

# must be root property
accesslog-application-name: idporten-oidc-demo-client

spring:
  application:
    name: idporten-oidc-demo-client
    environment: default

info:
  version: '@project.version@'
management:
  server:
    port: 8090
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      application: "idporten-oidc-demo-client"
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      basePath: /
      path-mapping:
        info: /version
oidc-demo-client:
  oidc-integration:
    connect-timeout-millis: 5000
    read-timeout-millis: 5000
    jwks-cache-lifetime-minutes: 60
    jwks-cache-refresh-minutes: 5
    issuer: https://issuer.idporten-utland.dev.digdir.no
    client-id: b7198ea6-14f0-488f-bb9a-206993ad28bc
    client-auth-method: client_secret_basic
    client-secret: 845c39db-4810-44d1-935c-81bd44bf6d98
    redirect-uri: http://127.0.0.1:7074/idporten-oidc-demo-client/callback
    post-logout-redirect-uri: http://127.0.0.1:7074/idporten-oidc-demo-client/logout/callback
---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'file:/etc/config/config.yaml'
      - 'optional:file:/etc/secret/secret.yaml'
server:
  port: 8080
