oidc-demo-client:
  features:
    authorization-details-enabled: true
  theme:
    user-id-claim: pid
    heading: Login with Ansattporten
    form-defaults:
      scope: openid
      acr-value: low
      ui-locale: en
  oidc-integration:
    connect-timeout-millis: 5000
    read-timeout-millis: 5000
    jwks-cache-lifetime-minutes: 60
    jwks-cache-refresh-minutes: 5
    issuer: https://issuer.idporten-utland.dev.digdir.no
    client-id: connect2norway_test_client_dev
    client-auth-method: client_secret_basic
    client-secret: 5acce044-ca8d-4729-9729-637f940ef779
    redirect-uri: http://localhost:7074/idporten-oidc-demo-client/callback
    post-logout-redirect-uri: http:/localhost:7074/idporten-oidc-demo-client/logout/callback

management:
  server:
    port: