---
spring:
  application:
    environment: systest

oidc-demo-client:
  features:
    use-pushed-authorization-requests: true
  theme:
    heading: Login with ID-porten (systest)
  oidc-integration:
    issuer: https://idporten.dev
    client-id: democlient_idporten_systest
    client-auth-method: client_secret_basic
    client-secret: ${OIDC_DEMO_CLIENT_SECRET}
    response-mode: query.jwt
    redirect-uri: https://demo-client.idporten.dev/callback
    post-logout-redirect-uri: https://demo-client.idporten.dev/logout/callback
  csp-header: "default-src 'self'; img-src 'self' data:; font-src 'self' cdn.jsdelivr.net; style-src 'self' cdn.jsdelivr.net; script-src 'self' cdn.jsdelivr.net; form-action 'self' login.idporten.dev idporten-connector.eidasnode.dev fullmakt.idporten.dev minidsi-integration.idporten.dev login.minid.dev;"

