---
spring:
  application:
    environment: systest

oidc-demo-client:
  features:
    use-pushed-authorization-requests: true
  theme:
    heading: Login with Ansattporten (systest)
  oidc-integration:
    issuer: https://ansattporten.dev
    client-id: testclient_ansattporten_openshift_azure
    client-auth-method: client_secret_basic
    client-secret: ${OIDC-CLIENT-SECRET}
    redirect-uri: https://demo-client.ansattporten.dev/callback
    post-logout-redirect-uri: https://demo-client.ansattporten.dev/logout/callback
  csp-header: "default-src 'self'; img-src 'self' data:; font-src 'self' cdn.jsdelivr.net; style-src 'self' cdn.jsdelivr.net; script-src 'self' cdn.jsdelivr.net; form-action 'self' login.ansattporten.dev;"
