---
server:
  port: 8080
  servlet:
    context-path: /
    session:
      tracking-modes:
        - cookie  # to block session via url

info:
  version: '@project.version@'

# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}
  endpoint:
    health:
      probes:
        enabled: true

oidc-demo-client:
  oidc-integration:
    connect-timeout-millis: 5000
    read-timeout-millis: 5000
    jwks-cache-lifetime-minutes: 60
    jwks-cache-refresh-minutes: 5
  csp-header: "style-src 'self' cdn.jsdelivr.net; script-src 'self' cdn.jsdelivr.net; form-action 'self' idporten:7070"

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'
