server:
  port: 7074
  servlet:
    context-path: /idporten-oidc-test-client
    session:
      tracking-modes:
        - cookie  #to block session via url
  tomcat:
    accesslog:
      directory: /var/log/idporten-oidc-test-client
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
  error:
    include-message: always
info:
  version: @project.version@

management:
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      application: "ID-porten OIDC test client"
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      basePath: /
      path-mapping:
        info: /version

oidc-test-client:
  oidc-integration:
    connect-timeout-millis: 5000
    read-timeout-millis: 5000
    jwks-cache-lifetime-minutes: 60
    jwks-cache-refresh-minutes: 5
    issuer: https://c2id-demo.westeurope.cloudapp.azure.com/c2id
    client-id: idporten-test-client
    client-auth-method: client_secret_basic
    client-secret: erTXmyi_hSy1Z1O-gJm9kto3-aNiczlJPveAoesuNg
    redirect-uri: https://c2id-demo.westeurope.cloudapp.azure.com/idporten-test-client/callback
    post-logout-redirect-uri: https://c2id-demo.westeurope.cloudapp.azure.com/idporten-test-client/logout/callback

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import: 'file:/etc/config/config.yaml'
server:
  port: 8080


