---
spring:
  application:
    environment: prod

oidc-demo-client:
  theme:
    heading: Login with Ansattporten (prod)
  oidc-integration:
    issuer: https://ansattporten.no
    client-id: ansattporten_demo_client_prod
    client-auth-method: client_secret_basic
    client-secret: ${OIDC_CLIENT_SECRET}
    redirect-uri: https://demo-client.ansattporten.no/callback
    post-logout-redirect-uri: https://demo-client.ansattporten.no/logout/callback
  csp-header: "default-src 'self'; img-src 'self' data:; font-src 'self' cdn.jsdelivr.net; style-src 'self' cdn.jsdelivr.net; script-src 'self' cdn.jsdelivr.net; form-action 'self' login.ansattporten.no altinn-orgvelger.ansattporten.no;"
