---
spring:
  application:
    environment: prod

oidc-demo-client:
  theme:
    heading: Login with ID-porten (prod)
  oidc-integration:
    issuer: https://idporten.no
    client-id: idporten_demo_client_prod
    client-auth-method: client_secret_basic
    client-secret: ${OIDC_DEMO_CLIENT_SECRET}
    redirect-uri: https://demo-client.idporten.no/callback
    post-logout-redirect-uri: https://demo-client.idporten.no/logout/callback
  csp-header: "default-src 'self'; style-src 'self' cdn.jsdelivr.net; script-src 'self' cdn.jsdelivr.net; form-action 'self' login.idporten.no;"
