server:
  port: 7074
  servlet:
    context-path: /idporten-oidc-test-client
    session:
      tracking-modes:
        - cookie  #to block session via url
  tomcat:
    accesslog:
      directory: /var/log/idporten-oidc-test-client
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
  error:
    include-message: always
info:
  version: @project.version@

management:
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      application: "ID-porten OIDC test client"
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      basePath: /
      path-mapping:
        info: /version

oidc-test-client:
  oidc-integration:
    connect-timeout-millis: 5000
    read-timeout-millis: 5000
    jwks-cache-lifetime-minutes: 60
    jwks-cache-refresh-minutes: 5
    issuer: https://c2id-demo.westeurope.cloudapp.azure.com/c2id
    client-id: b7198ea6-14f0-488f-bb9a-206993ad28bc
    client-auth-method: client_secret_basic
    client-secret: 845c39db-4810-44d1-935c-81bd44bf6d98
    redirect-uri: http://127.0.0.1:7074/idporten-oidc-test-client/callback
    post-logout-redirect-uri: http://127.0.0.1:7074/idporten-oidc-test-client/logout/callback

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'file:/etc/config/config.yaml'
      - 'optional:file:/etc/secret/secret.yaml'
server:
  port: 8080


