# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/publish Docker image & update image version in config

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'src/test/**'
    - 'docker/**'
    - 'docker-compose.yaml'
    - '*.md'
    - 'LICENSE'

jobs:
  build-publish-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      image-name: idporten-oidc-demo-client
      java-version: 21
    secrets: inherit
  update-image-version:
    uses: felleslosninger/github-workflows/.github/workflows/ci-update-image-version.yml@main
    needs: build-publish-image
    with:
      application-name: idporten-oidc-demo-client,ansattporten-oidc-demo-client
      image-version: ${{ needs.build-publish-image.outputs.image-version }}
      image-digest: ${{ needs.build-publish-image.outputs.image-digest }}
    secrets: inherit

