# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build/publish Docker image & update image version in config

on:
  push:
    branches: [main]
    paths-ignore:
      - "src/test/**"
      - "docker/**"
      - "docker-compose.yaml"
      - "*.md"
      - "LICENSE"
      - "catalog-info.yaml"

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      image-name: idporten-oidc-demo-client
      java-version: 21
    secrets: inherit

  call-update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: call-workflow-image-build-publish
    strategy:
      matrix:
        application-name: [idporten-oidc-demo-client, ansattporten-oidc-demo-client, eidas-oidc-demo-client]
        include:
          - application-name: idporten-oidc-demo-client
            product-name: idporten
          - application-name: ansattporten-oidc-demo-client
            product-name: ansattporten
          - application-name: eidas-oidc-demo-client
            product-name: eidas
    with:
      application-name: ${{ matrix.application-name }}
      deployment-environment: systest
      image-digest: ${{ needs.call-workflow-image-build-publish.outputs.image-digest }}
      image-name: idporten-oidc-demo-client
      image-version: ${{ needs.call-workflow-image-build-publish.outputs.image-version }}
      kubernetes-repo: idporten-cd
      product-name: ${{ matrix.product-name }}
    secrets: inherit
